openapi: 3.0.0
info:
  title: Sample API
  version: 0.0.1

components:
  schemas:
    Flow:
      title: Flow object
      type: object
      properties:
        srcIp:
          type: string
        dstIp:
          type: string

paths:
  /flows:
    get:
      summary: Returns a list of flows.
      responses:
        '200':
          description: A JSON array of user names
    put:
      summary: Try to register new flow
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Flow'
      responses:
        '200':
          description: A JSON array of user names
